require('dotenv').config();

module.exports = {
  GUILD_ID: process.env.GUILD_ID,
  WELCOME_CHANNEL_ID: process.env.WELCOME_CHANNEL_ID,
  INTRODUCTION_CHANNEL_ID: process.env.INTRODUCTION_CHANNEL_ID,
  CODE_OF_CONDUCT_MESSAGE_ID: process.env.CODE_OF_CONDUCT_MESSAGE_ID,
  GERMINATING_ROLE_ID: process.env.GERMINATING_ROLE_ID,
  SEEDLING_ROLE_ID: process.env.SEEDLING_ROLE_ID,
  MIN_INTRO_MESSAGE_LENGTH: process.env.MIN_INTRO_MESSAGE_LENGTH,
};
